In [11]:
import numpy as np
import numpy.polynomial as nppoly

In [34]:
def index_n(ind, bases=np.array([10])):
    powers = np.cumprod(np.insert(bases,0,1))
    ind_n = np.floor_divide(np.remainder(ind, powers[1:]), powers[:-1] )
    return ind_n

## Examples:

In [35]:
# Each digit in the reverse order
index_n(12345, bases=np.array([10,10,10,10,10]) )

array([5, 4, 3, 2, 1], dtype=int32)

In [36]:
for ind in range(4*3*2-1):
    print( index_n(ind, bases=np.array([4,3,2])) )

[0 0 0]
[1 0 0]
[2 0 0]
[3 0 0]
[0 1 0]
[1 1 0]
[2 1 0]
[3 1 0]
[0 2 0]
[1 2 0]
[2 2 0]
[3 2 0]
[0 0 1]
[1 0 1]
[2 0 1]
[3 0 1]
[0 1 1]
[1 1 1]
[2 1 1]
[3 1 1]
[0 2 1]
[1 2 1]
[2 2 1]


In [16]:
ghq_sizes = np.array([4,3,2])

z_list = []
w_list = []

for size in ghq_sizes:
    z, w = nppoly.hermite_e.hermegauss(deg=size)
    w = w / np.sqrt(2.0*np.pi)
    z_list.append( z )
    w_list.append( w )

In [92]:
for ind in range(np.prod(ghq_sizes)-1):
    ind_n = index_n(ind, bases=ghq_sizes)
    z_vec = np.array( list(map(lambda ind_k:z_list[ind_k[0]][ind_k[1]], zip(range(3),ind_n))) )
    weight = 
    print( ind_n, z_vec )

[0 0 0] [-2.33441422 -1.73205081 -1.        ]
[1 0 0] [-0.74196378 -1.73205081 -1.        ]
[2 0 0] [ 0.74196378 -1.73205081 -1.        ]
[3 0 0] [ 2.33441422 -1.73205081 -1.        ]
[0 1 0] [-2.33441422  0.         -1.        ]
[1 1 0] [-0.74196378  0.         -1.        ]
[2 1 0] [ 0.74196378  0.         -1.        ]
[3 1 0] [ 2.33441422  0.         -1.        ]
[0 2 0] [-2.33441422  1.73205081 -1.        ]
[1 2 0] [-0.74196378  1.73205081 -1.        ]
[2 2 0] [ 0.74196378  1.73205081 -1.        ]
[3 2 0] [ 2.33441422  1.73205081 -1.        ]
[0 0 1] [-2.33441422 -1.73205081  1.        ]
[1 0 1] [-0.74196378 -1.73205081  1.        ]
[2 0 1] [ 0.74196378 -1.73205081  1.        ]
[3 0 1] [ 2.33441422 -1.73205081  1.        ]
[0 1 1] [-2.33441422  0.          1.        ]
[1 1 1] [-0.74196378  0.          1.        ]
[2 1 1] [ 0.74196378  0.          1.        ]
[3 1 1] [ 2.33441422  0.          1.        ]
[0 2 1] [-2.33441422  1.73205081  1.        ]
[1 2 1] [-0.74196378  1.73205081  